### ISSUE TITLE
Same structure for an Android Project?

### ISSUE THREAD

**Issue by blundell** [jjohannes/understanding-gradle#1]
![image](https://user-images.githubusercontent.com/655860/135729900-01db4fbc-f265-4534-953f-2d7e2fd1cb1b.png)

I can't get this structure to work for an Android project. Do you expect it to?

as in, having 3 projects in AndroidStudio (`my-project`(android), `my-other-project`, `my-build-logic`) at the root. I get errors about it "not being a gradle based project".

The way I have seen it before is having the android app as root and other folders(projects) inside like:

/my-project (android)
--/my-build-logic

**Comment by jjohannes** [comment]
In this setup and example `my-project` is the main project. You have to open `03_Plugins/my-project` in IDEA / Android Studio. See [Explore this sample](https://github.com/jjohannes/understanding-gradle/tree/main/03_Plugins#explore-this-sample) in the README.

I choose this structure for the sample to emphasise that `my-project`, `my-other-project` and `my-build-logic` are separate builds that can be placed in independent locations.

If you have one "main" build that you want to place in the root of your repository and add a _build-logic_ build to it, you can use the structure you propose above. It's also totally fine and a very common approach.

**Comment by blundell** [comment]
Yeah I really like your project structure and I want to use it, that's why I am trying to get it to work :-) but to try something even simpler, if I make a new Android project, then move all the files down one level into `my-project`, it's no longer recognised, you can see the run configuration can't see the Android module, and the IDE can't recognise the project.

![image](https://user-images.githubusercontent.com/655860/135743962-73933566-48da-41aa-9eb1-e1783a499d04.png)

Apart from being Android based, I can't see a difference?

**Comment by blundell** [comment]
and if I delete the other files from the root folder, I get: 

![image](https://user-images.githubusercontent.com/655860/135744094-4102796e-48ee-491a-8e34-7e5d5efec3a4.png)

**Comment by jjohannes** [comment]
What I mean is: 
- After you created the project and moved the files into "my-project", close the project.
- Then open the `my-project` folder (!) as the Project in Android Studio (**not** the `multiproject` folder!)

Android Studio will import included other builds (like `my-build-logic`) and show them even if they are not subfolders of the project you open. That's the same I do in IntelliJ in my videos.

<img width="395" alt="as2" src="https://user-images.githubusercontent.com/1963746/135746208-ead87d0b-6f52-4aae-9acc-3bf1a582db79.png">

<img width="410" alt="as1" src="https://user-images.githubusercontent.com/1963746/135746217-638dbc58-3037-4ceb-8ca8-873469fb058a.png">

**Comment by blundell** [comment]
ah! Now that makes sense! Got it, thank you very much :-)
