### ISSUE TITLE
pluginManagement block must appear before any other statement

### ISSUE THREAD

**Issue by blundell** [jjohannes/understanding-gradle#2]
![image](https://user-images.githubusercontent.com/655860/135731097-c34c3fe6-e3d7-400c-b790-b2bf44a7b437.png)

^ when I try the above in my Android project I get:

```
> startup failed:
  settings file '/path/to/my-app/settings.gradle': 3: 
The pluginManagement {} block must appear before any other statements in the script.
```

and so I have to move the `rootProject.name` line below the `pluginManagement` block

But with such a simple setup, why is mine acting different to yours?

**Comment by jjohannes** [comment]
Thanks for the feedback. I assume you are using the Groovy DSL (`.gradle` extension) while I use the Kotlin DSL (`.gradle.kts` extension).

This is one of the (annoying) small differences between the DSLs I forgot about.

I will adjust the samples so that the settings file works in both DSLs.
